- name: Deploy site
  become: true
  block:
    - name: Create project directory
      ansible.builtin.file:
        path: "/opt/containers/ansible/{{ site_name }}"
        state: directory
        mode: '0755'
        recurse: true
      become: true

    - name: Copy Docker Compose template
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/compose.yaml.j2"
        dest: "/opt/containers/ansible/{{ site_name }}/docker-compose.yml"
        mode: '0644'
      become: true

    - name: Compile bundle in Docker container
      ansible.builtin.command:
        cmd: >
          docker run --rm
          -v "{{ playbook_dir }}/../app/:/app"
          node:latest
          /bin/bash -c "cd /app && npm install && npm run build"
      become: true
      register: compile_result
      failed_when: compile_result.rc != 0

    - name: Copy www directory
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../app/out/"
        dest: "/opt/containers/ansible/{{ site_name }}/www/"
        mode: '0644'
      become: true

    - name: Pull Docker images
      community.docker.docker_compose_v2:
        project_src: "/opt/containers/ansible/{{ site_name }}"
        files:
          - "docker-compose.yml"
        pull: always
        state: present
      become: true

    - name: Start Docker containers
      community.docker.docker_compose_v2:
        project_src: "/opt/containers/ansible/{{ site_name }}"
        files:
          - "docker-compose.yml"
        state: present
        pull: always
      become: true
