site_name: "isaac_cc_store"
site_prefix: "app"
django_dir: "{{ playbook_dir }}/../app"
dockerhub_user: "scootekunst"
image_name: "{{ dockerhub_user }}/{{ site_name }}-{{env}}"
nginx_image: "{{ dockerhub_user }}/{{ site_name }}-nginx-{{env}}"

certbot_email: "isaac@isaac.cc"

postgres_user: "{{ site_name}}_db_user"
postgres_db: "{{ site_name}}_db"

admin_email: "admin@isaac.cc"

email_host: "smtp.gmail.com"
email_port: 587
email_use_tls: true
email_host_user: "admin@isaac.cc"
allowed_hosts: "localhost, 127.0.0.1,{{domain}}"

nginx_port: 11480


acme_challenge_type: http-01
acme_directory: https://acme-v02.api.letsencrypt.org/directory
acme_version: 2
acme_email: "{{ certbot_email }}"
letsencrypt_dir: /etc/letsencrypt
letsencrypt_keys_dir: /etc/letsencrypt/keys
letsencrypt_csrs_dir: /etc/letsencrypt/csrs
letsencrypt_certs_dir: /etc/letsencrypt/certs
letsencrypt_account_key: /etc/letsencrypt/account/account.key
domain_name: "{{ domain }}"


# List of initial secrets to generate
initial_secrets:
include_vars:
  file: "{{ playbook_dir }}/group_vars/all/shared_vars.yml"
